// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBs3_PwlvReZWf2Z6MKqvD-IeRUb2ccbY',
    appId: '1:653045279746:web:14727576ef324033ed4b1b',
    messagingSenderId: '653045279746',
    projectId: 'auto-controlsmart',
    authDomain: 'auto-controlsmart.firebaseapp.com',
    storageBucket: 'auto-controlsmart.appspot.com',
    measurementId: 'G-S0FZ2Y1GFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjFVQm-SkWTdClYA6zIovPyJ5Lhr0420',
    appId: '1:653045279746:android:d1ed92e141418273ed4b1b',
    messagingSenderId: '653045279746',
    projectId: 'auto-controlsmart',
    storageBucket: 'auto-controlsmart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLE6kPLeK2fgaJgWurI_giEfevFIJ4I0s',
    appId: '1:653045279746:ios:12e1b5a6ce01ce39ed4b1b',
    messagingSenderId: '653045279746',
    projectId: 'auto-controlsmart',
    storageBucket: 'auto-controlsmart.appspot.com',
    iosBundleId: 'com.example.smart.control',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLE6kPLeK2fgaJgWurI_giEfevFIJ4I0s',
    appId: '1:653045279746:ios:265f526d000170fbed4b1b',
    messagingSenderId: '653045279746',
    projectId: 'auto-controlsmart',
    storageBucket: 'auto-controlsmart.appspot.com',
    iosBundleId: 'com.example.smart.control.RunnerTests',
  );
}
